// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://snaxoetkenbbgipmihpc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNuYXhvZXRrZW5iYmdpcG1paHBjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MDUwOTAsImV4cCI6MjA3MjM4MTA5MH0.L13HhvQMrha6XGiL9uykPFCrmBqB61E0N4Oo0wY0tg0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});